name: Build on Windows

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

defaults:
  run:
    shell: msys2 {0}

jobs:
  build-cmake:
    name: CMake UCRT-x86_64
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        install: base-devel git mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-ninja mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-boost mingw-w64-ucrt-x86_64-openssl mingw-w64-ucrt-x86_64-miniupnpc
        update: true

    - name: Build application
      run: |
        cmake -DWITH_GIT_VERSION=ON -DWITH_STATIC=ON -DWITH_UPNP=ON -DCMAKE_BUILD_TYPE=Release .
        cmake --build . -- -j3

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: i2pd-windows-ucrt
        path: |
          ./i2pd.exe
          ./vain.exe
          ./keygen.exe
          ./keyinfo.exe
          ./famtool.exe
          ./routerinfo.exe
          ./regaddr.exe
          ./regaddr_3ld.exe
          ./i2pbase64.exe
          ./offlinekeys.exe
          ./b33address.exe
          ./regaddralias.exe
          ./x25519.exe
          ./verifyhost.exe
          ./autoconf.exe

