name: Build on macOS

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-cmake:
    name: CMake with -DWITH_UPNP=ON
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        brew update
        brew install boost miniupnpc openssl@1.1 zlib

    - name: Configure and build with CMake
      run: |
        mkdir build
        cd build
        cmake \
          -DWITH_UPNP=ON \
          -DOPENSSL_ROOT_DIR="$HOMEBREW_PREFIX/opt/openssl@1.1" \
          -DBOOST_ROOT="$HOMEBREW_PREFIX/opt/boost" \
          -DCMAKE_PREFIX_PATH="$HOMEBREW_PREFIX/opt/boost;$HOMEBREW_PREFIX/opt/miniupnpc;$HOMEBREW_PREFIX/opt/openssl@1.1" \
          -DZLIB_ROOT=$(brew --prefix zlib) \
          -DCMAKE_BUILD_TYPE=Release \
          -DFIND_BOOST_USE_CONFIG=OFF \
          ..
        make -j8

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: i2pd-macos
        path: |
          build/i2pd
          build/vain
          build/keygen
          build/keyinfo
          build/famtool
          build/routerinfo
          build/regaddr
          build/regaddr_3ld
          build/i2pbase64
          build/offlinekeys
          build/b33address
          build/regaddralias
          build/x25519
          build/verifyhost
          build/autoconf

