name: Build on Windows

on:
  push:
    branches:
    - '*'
    paths:
    - .github/workflows/build-windows.yml
    - build/CMakeLists.txt
    - build/cmake_modules/**
    - daemon/**
    - i18n/**
    - libi2pd/**
    - libi2pd_client/**
    - Win32/**
    - Makefile
    - Makefile.mingw
    tags:
    - '*'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

defaults:
  run:
    shell: msys2 {0}

jobs:
  build-cmake:
    name: CMake ${{ matrix.arch }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: UCRT64, arch: ucrt-x86_64, arch_short: x64-ucrt, compiler: gcc },
          { msystem: CLANG64, arch: clang-x86_64, arch_short: x64-clang, compiler: clang },
          { msystem: MINGW64, arch: x86_64, arch_short: x64, compiler: gcc },
          { msystem: MINGW32, arch: i686, arch_short: x86, compiler: gcc }
        ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        install: base-devel git mingw-w64-${{ matrix.arch }}-cmake mingw-w64-${{ matrix.arch }}-ninja mingw-w64-${{ matrix.arch }}-${{ matrix.compiler }} mingw-w64-${{ matrix.arch }}-boost mingw-w64-${{ matrix.arch }}-openssl mingw-w64-${{ matrix.arch }}-miniupnpc
        update: true

    - name: Build application
      run: |
        cmake -DWITH_GIT_VERSION=ON -DWITH_STATIC=ON -DWITH_UPNP=ON -DCMAKE_BUILD_TYPE=Release .
        cmake --build . -- -j3

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: i2pd-cmake-${{ matrix.arch_short }}.exe
        path: |
          ./i2pd.exe
          ./vain.exe
          ./keygen.exe
          ./keyinfo.exe
          ./famtool.exe
          ./routerinfo.exe
          ./regaddr.exe
          ./regaddr_3ld.exe
          ./i2pbase64.exe
          ./offlinekeys.exe
          ./b33address.exe
          ./regaddralias.exe
          ./x25519.exe
          ./verifyhost.exe
          ./autoconf.exe

