name: Build on macOS

on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/build-osx.yml
      - build/CMakeLists.txt
      - build/cmake_modules/**
      - daemon/**
      - i18n/**
      - libi2pd/**
      - libi2pd_client/**
      - CMakeLists.txt
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-cmake:
    name: CMake with -DWITH_UPNP=${{ matrix.with_upnp }}
    runs-on: macOS-latest

    strategy:
      fail-fast: true
      matrix:
        with_upnp: ['ON', 'OFF']

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        brew update
        brew install boost miniupnpc openssl@1.1 zlib

    - name: Configure and build with CMake
      run: |
        mkdir build
        cd build
        cmake \
          -DWITH_UPNP=${{ matrix.with_upnp }} \
          -DOPENSSL_ROOT_DIR="$HOMEBREW_PREFIX/opt/openssl@1.1" \
          -DBOOST_ROOT="$HOMEBREW_PREFIX/opt/boost" \
          -DCMAKE_PREFIX_PATH="$HOMEBREW_PREFIX/opt/boost;$HOMEBREW_PREFIX/opt/miniupnpc;$HOMEBREW_PREFIX/opt/openssl@1.1" \
          -DCMAKE_BUILD_TYPE=Release \
          -DFIND_BOOST_USE_CONFIG=OFF \
          ..

