name: Build on Ubuntu

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  build-cmake:
    name: CMake with -DWITH_UPNP=ON
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get install build-essential cmake libboost-all-dev libminiupnpc-dev libssl-dev zlib1g-dev

    - name: build application
      run: |
        mkdir build
        cd build
        cmake -DWITH_UPNP=ON ..
        make -j3

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: i2pd-ubuntu
        path: |
          build/i2pd
          build/vain
          build/keygen
          build/keyinfo
          build/famtool
          build/routerinfo
          build/regaddr
          build/regaddr_3ld
          build/i2pbase64
          build/offlinekeys
          build/b33address
          build/regaddralias
          build/x25519
          build/verifyhost
          build/autoconf
