name: Continuous Release

on:
  workflow_run:
    workflows: ["Build on Ubuntu", "Build on macOS", "Build on FreeBSD", "Build on Windows"]
    types:
      - completed
  # Allow manual triggering
  workflow_dispatch:

jobs:
  release:
    name: Create Continuous Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Only run when triggered by workflow_run or manually
    if: ${{ github.event_name == 'workflow_run' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          if [ -d "artifacts" ]; then
            find artifacts -type f
            echo ""
            echo "Artifact directories:"
            ls -la artifacts/
          else
            echo "No artifacts directory found"
          fi

      - name: Create release directory structure
        run: |
          mkdir -p releases/{linux,freebsd,macos,windows}
          
      - name: Organize Linux artifacts
        run: |
          # Find and copy Linux artifacts (Ubuntu/CMake builds)
          if [ -d "artifacts/i2pd-ubuntu" ]; then
            cp -r "artifacts/i2pd-ubuntu" "releases/linux/ubuntu" 
            echo "Copied Linux artifact: ubuntu"
            
            # Create compressed archive for Linux build
            tar -czf "i2pd-linux-ubuntu.tar.gz" -C releases/linux/ubuntu .
            echo "Created Linux archive: i2pd-linux-ubuntu.tar.gz"
          fi

      - name: Organize FreeBSD artifacts
        run: |
          # Copy FreeBSD artifacts
          if [ -d "artifacts/i2pd-freebsd" ]; then
            cp -r "artifacts/i2pd-freebsd" releases/freebsd/
            echo "Copied FreeBSD artifacts"
            
            # Create compressed archive for FreeBSD
            tar -czf i2pd-freebsd.tar.gz -C releases/freebsd i2pd-freebsd
            echo "Created FreeBSD archive: i2pd-freebsd.tar.gz"
          fi

      - name: Organize macOS artifacts
        run: |
          # Find and copy macOS artifacts
          if [ -d "artifacts/i2pd-macos" ]; then
            cp -r "artifacts/i2pd-macos" "releases/macos/macos"
            echo "Copied macOS artifact: macos"
            
            # Create compressed archive for macOS build
            tar -czf "i2pd-macos-macos.tar.gz" -C releases/macos/macos .
            echo "Created macOS archive: i2pd-macos-macos.tar.gz"
          fi

      - name: Organize Windows artifacts
        run: |
          # Find and copy Windows artifacts by architecture
          if [ -d "artifacts" ]; then
            for dir in artifacts/i2pd-windows-*; do
              if [ -d "$dir" ]; then
                name=$(basename "$dir")
                cp -r "$dir" "releases/windows/${name}"
                echo "Copied Windows artifact: $name"
              fi
            done
            
            # Create ZIP archives for each Windows build
            for dir in releases/windows/*; do
              if [ -d "$dir" ]; then
                name=$(basename "$dir")
                cd "$dir"
                zip -r "../i2pd-windows-$name.zip" *.exe
                cd ../..
                echo "Created Windows archive: i2pd-windows-$name.zip"
              fi
            done
          fi

      - name: Prepare release assets
        run: |
          echo "Listing all release assets:"
          ls -la *.tar.gz *.zip 2>/dev/null || echo "No release assets found"
          
      - name: Create or Update Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: ${{ contains(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
        with:
          tag_name: ${{ github.ref_name || format('continuous-{0}', github.run_id) }}
          name: ${{ github.ref_name || format('Continuous Release {0}', github.run_id) }}
          body: |
            Continuous Release Build
            
            Workflow Run: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            
            This release contains build artifacts for multiple platforms:
            - Linux (with UPnP ON)
            - FreeBSD
            - macOS (with UPnP ON)
            - Windows (multiple architectures: x64-ucrt, x64-clang, x64, x86)
            
            Artifacts include the main executable and all associated utilities.
          draft: false
          prerelease: true
          files: |
            *.tar.gz
            *.zip