name: Continuous Release

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  workflow_run:
    workflows: ["Build on Ubuntu", "Build on macOS", "Build on FreeBSD", "Build on Windows"]
    types:
      - completed

jobs:
  release:
    name: Create Continuous Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event_name == 'workflow_run' || (github.event_name == 'push' && (github.ref_type == 'tag' || github.ref_type == 'branch')) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          find artifacts -type f
          echo ""
          echo "Artifact directories:"
          ls -la artifacts/

      - name: Create release directory structure
        run: |
          mkdir -p releases/{linux,freebsd,macos,windows}
          
      - name: Organize Linux artifacts
        run: |
          # Find and copy Linux artifacts (Ubuntu/CMake builds)
          for dir in artifacts/i2pd-ubuntu-*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              cp -r "$dir" "releases/linux/${name}" 
              echo "Copied Linux artifact: $name"
            fi
          done
          
          # Create compressed archives for each Linux build
          for dir in releases/linux/*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              tar -czf "i2pd-linux-$name.tar.gz" -C releases/linux "$name"
              echo "Created Linux archive: i2pd-linux-$name.tar.gz"
            fi
          done

      - name: Organize FreeBSD artifacts
        run: |
          # Copy FreeBSD artifacts
          if [ -d "artifacts/i2pd-freebsd" ]; then
            cp -r "artifacts/i2pd-freebsd" releases/freebsd/
            echo "Copied FreeBSD artifacts"
            
            # Create compressed archive for FreeBSD
            tar -czf i2pd-freebsd.tar.gz -C releases/freebsd i2pd-freebsd
            echo "Created FreeBSD archive: i2pd-freebsd.tar.gz"
          fi

      - name: Organize macOS artifacts
        run: |
          # Find and copy macOS artifacts
          for dir in artifacts/i2pd-macos-*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              cp -r "$dir" "releases/macos/${name}"
              echo "Copied macOS artifact: $name"
            fi
          done
          
          # Create compressed archives for each macOS build
          for dir in releases/macos/*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              tar -czf "i2pd-macos-$name.tar.gz" -C releases/macos "$name"
              echo "Created macOS archive: i2pd-macos-$name.tar.gz"
            fi
          done

      - name: Organize Windows artifacts
        run: |
          # Find and copy Windows artifacts by architecture
          for dir in artifacts/i2pd-windows-*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              cp -r "$dir" "releases/windows/${name}"
              echo "Copied Windows artifact: $name"
            fi
          done
          
          # Create ZIP archives for each Windows build
          for dir in releases/windows/*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              cd "$dir"
              zip -r "../i2pd-windows-$name.zip" *.exe
              cd ../..
              echo "Created Windows archive: i2pd-windows-$name.zip"
            fi
          done

      - name: Prepare release assets
        run: |
          echo "Listing all release assets:"
          ls -la *.tar.gz *.zip 2>/dev/null || echo "No tar.gz or zip files found"
          
      - name: Create or Update Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || (github.event_name == 'workflow_run' && format('continuous-{0}', github.sha)) || format('continuous-{0}', github.sha) }}
          name: ${{ github.ref_type == 'tag' && format('Release {0}', github.ref_name) || 'Continuous Release' }}
          body: |
            Continuous Release Build
            
            Commit: ${{ github.sha }}
            
            This release contains build artifacts for multiple platforms:
            - Linux (with UPnP ON/OFF configurations)
            - FreeBSD
            - macOS (with UPnP ON/OFF configurations)
            - Windows (multiple architectures: x64-ucrt, x64-clang, x64, x86)
            
            Artifacts include the main executable and all associated utilities.
          draft: false
          prerelease: ${{ github.ref_type != 'tag' }}
          files: |
            *.tar.gz
            *.zip