name: Continuous Release

on:
  workflow_run:
    workflows: ["Build on Ubuntu", "Build on macOS", "Build on FreeBSD", "Build on Windows"]
    types:
      - completed
  # Allow manual triggering and also run on every push to any branch
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  release:
    name: Create Continuous Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Run when triggered by workflow_run, manually, or on any push
    if: ${{ github.event_name == 'workflow_run' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_type == 'branch') }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          if [ -d "artifacts" ]; then
            find artifacts -type f
            echo ""
            echo "Artifact directories:"
            ls -la artifacts/
          else
            echo "No artifacts directory found"
          fi

      - name: Create release directory structure
        run: |
          mkdir -p releases/{linux,freebsd,macos,windows}
          
      - name: Organize Linux artifacts
        run: |
          # Find and copy Linux artifacts (Ubuntu/CMake builds)
          if [ -d "artifacts/i2pd-ubuntu" ]; then
            cp -r "artifacts/i2pd-ubuntu" "releases/linux/ubuntu" 
            echo "Copied Linux artifact: ubuntu"
            
            # Create compressed archive for Linux build
            tar -czf "i2pd-linux-ubuntu.tar.gz" -C releases/linux/ubuntu .
            echo "Created Linux archive: i2pd-linux-ubuntu.tar.gz"
          fi

      - name: Organize FreeBSD artifacts
        run: |
          # Copy FreeBSD artifacts
          if [ -d "artifacts/i2pd-freebsd" ]; then
            cp -r "artifacts/i2pd-freebsd" releases/freebsd/
            echo "Copied FreeBSD artifacts"
            
            # Create compressed archive for FreeBSD
            tar -czf i2pd-freebsd.tar.gz -C releases/freebsd i2pd-freebsd
            echo "Created FreeBSD archive: i2pd-freebsd.tar.gz"
          fi

      - name: Organize macOS artifacts
        run: |
          # Find and copy macOS artifacts
          if [ -d "artifacts/i2pd-macos" ]; then
            cp -r "artifacts/i2pd-macos" "releases/macos/macos"
            echo "Copied macOS artifact: macos"
            
            # Create compressed archive for macOS build
            tar -czf "i2pd-macos-macos.tar.gz" -C releases/macos/macos .
            echo "Created macOS archive: i2pd-macos-macos.tar.gz"
          fi

      - name: Organize Windows artifacts
        run: |
          # Find and copy Windows UCRT artifact
          if [ -d "artifacts/i2pd-windows-ucrt" ]; then
            cp -r "artifacts/i2pd-windows-ucrt" "releases/windows/ucrt" 
            echo "Copied Windows UCRT artifact"
            
            # Create ZIP archive for Windows build
            cd "releases/windows/ucrt"
            zip -r "../../i2pd-windows-ucrt.zip" *.exe
            cd ../../..
            echo "Created Windows archive: i2pd-windows-ucrt.zip"
          fi

      - name: Prepare release assets
        run: |
          echo "Listing all release assets:"
          ls -la *.tar.gz *.zip 2>/dev/null || echo "No release assets found"
          
      - name: Create or Update Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'workflow_run' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_type == 'branch') }}
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || format('continuous-{0}', github.sha) }}
          name: ${{ github.ref_type == 'tag' && github.ref_name || format('Continuous Release {0}', github.sha) }}
          body: |
            Continuous Release Build
            
            Workflow Run: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            
            This release contains build artifacts for multiple platforms:
            - Linux (with UPnP ON)
            - FreeBSD
            - macOS (with UPnP ON)
            - Windows (UCRT x64 variant)
            
            Artifacts include the main executable and all associated utilities.
          draft: false
          prerelease: true
          files: |
            *.tar.gz
            *.zip